- name: System packages
  become: true
  apt:
    name: [ "python3", "python3-pip", "man-db", "git", "zsh", "zplug" ]
  tags:
    - core
    - server
    - station
- name: Workstation system packages
  become: true
  apt:
    name: [ "xorg", "xinit", "i3" ]
  tags: 
    - core
    - station
- name: Basic utilities
  become: true
  apt:
    name: [ "curl", "sed", "gawk", "stow" ]
  tags: 
    - core
    - server
    - station
- name: Productivity tools
  become: true
  apt:
    name: [ "tmux", "fzf", "jq", "ripgrep" ]
  tags:
    - core
    - productivity
    - server
    - station
- name: Change to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: 
    - core
    - station
- name: Reset playbook url
  shell: cd ~/projects/ncko/debian-playbook && git remote set-url origin git@github.com:ncko/debian-playbook
  tags: 
    - station
- name: Create deck direction
  shell: mkdir -p ~/deck
  tags: 
    - station
    - server
- name: Create Downloads directory
  shell: mkdir -p ~/deck ~/Downloads
  tags: 
    - station
