- name: System packages
  become: true
  apt:
    name: [ "python3", "python3-pip", "xorg", "xinit", "i3", "man-db", "git" ]
- name: Productivity tools
  become: true
  apt:
    name: [ "tmux", "fzf", "neovim" ]
