- name: System packages
  become: true
  apt:
    name: [ "python3", "python3-pip", "xorg", "xinit", "i3", "man-db", "git", "zsh", "zplug" ]
  tags: core
- name: Basic utilities
  become: true
  apt:
    name: [ "curl", "sed", "gawk", "stow" ]
  tags: core
- name: Productivity tools
  become: true
  apt:
    name: [ "tmux", "fzf", "jq" ]
  tags:
    - core
    - productivity
- name: Change to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: core
- name: Reset playbook url
  shell: cd ~/projects/ncko/debian-playbook && git remote set-url origin git@github.com:ncko/debian-playbook
