- name: Install dependencies
  become: true
  apt:
    name: [ "nodejs" ]
  tags:
    - cron
- name: Clone greensquares
  ansible.builtin.git:
    repo: git@github.com:ncko/greensquares
    dest: /home/ncko/projects/ncko/greensquares
  tags:
    - cron
- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
  tags:
    - cron
- name: Install greensquares packages
  community.general.yarn:
    path: /home/ncko/projects/ncko/greensquares
  tags:
    - cron
- name: Setup crontab for greensquares
  ansible.builtin.cron:
    name: "greensquares"
    minute: "13"
    hour: "5"
    weekday: "0,1,2,3,4,5"
    job: "cd /home/ncko/projects/ncko/greensquares && node index.js > /tmp/greensquares.log"
  tags:
    - cron
