- name: clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/ncko/debian-dotfiles
    dest: ~/.dotfiles
- name: install dotfiles
  shell: ~/.dotfiles/station install
- name: reset dotfiles repo origin url
  shell: cd ~/.dotfiles && git remote set-url origin git@github.com:ncko/debian-dotfiles
