- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "hello@ncko.me"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "ncko"
- name: Git default editor
  git_config:
    name: core.editor
    scope: global
    value: "nvim"
